# Site settings
title: Mehdi Merbah
email: mehdimerbah@outlook.com

description: >
  Bioinformatician and data science enthusiast. In pursuit of the next intriguing rabbit hole.
baseurl: ""
url: "https://mehdimerbah.github.io"

# Socials
github_username: mehdimerbah
linkedin_username: mehdi-merbah

# Build settings
markdown: kramdown
theme: minima

# Navigation order
header_pages:
  - experience.md
  - research.md
  - blog.md
  - readings.md

plugins:
  - jekyll-feed



