# Site settings
title: Mehdi Merbah
email: mehdimerbah@outlook.com

description: >
  Bioinformatics researcher interested in computational biology, machine learning, and topological data analysis.
baseurl: ""
url: "https://mehdimerbah.github.io"

# Socials
github_username: mehdimerbah
linkedin_username: mehdi-merbah

# Build settings
markdown: kramdown
theme: minima

# Navigation order
header_pages:
  - research.md
  - blog.md
  - readings.md

plugins:
  - jekyll-feed



